name: Deploy to Cloud Run
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0.6.0
        with:
          service: frontend-web
          source: .
          region: asia-east1
          credentials: ${{ secrets.CHT_FIVEG_GCP_SA_KEY  }}
